import "@/styles/globals.css";
import { Metadata } from "next";
import React from "react";

import { TrpcProvider } from "@/app/TrpcProvider";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ここでは、すべてのページを TrpcProvider でラップして、クライアントが RPC を呼び出せるようにします

/**
 * ルートレイアウトコンポーネント
 * @param {Object} props - ルートレイアウトコンポーネントのプロパティ
 * @param {React.ReactNode} props.children - 子要素
 * @return {JSX.Element} - ルートレイアウトコンポーネントのJSX要素
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <TrpcProvider>
      <html lang="ja" suppressHydrationWarning>
        <body>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </TrpcProvider>
  );
}
